---
title: "Advanced Bioinformatics 2021 assessment"
author: "m1906710"
date: "14/04/2021"
output: html_document
---

# Task 1
```{r}
x = 5:55
# represents the numbers from 5 to 55
sum (x)
# This is the sum of numbers from 5 to 55
 
```

# Task 2
```{r}
sumfun <- function(n)
  sum(5:n)
# assigned variable sumfun the function n.

sumfun(10)
# sum(5:10). Sum of numbers from 5 to 10

sumfun(20)
# sum(5:20). Sum of numbers from 5 to 20

sumfun(100)
# sum(5:100). Sum of numbers from 5 to 100

```

# Task 3
```{r}
# Fibonaaci series
Flare <- function(a) {
  if(a <= 1) {
    return(a)
  } else {
    return(Flare(a-1) + Flare(a-2))
  }
}
# Assigned vaiable Flare the function a.
# Function a is returned if the a function is less or equal to 1. Otherwise the function a -1 added to the function a -2 is returned.
for(x in 1:12){
print(Flare(x))
}
# The for loop where the loop variable is x and expression 1 is numbers 1 to 12 using the operator :. Expression 2 prints function a in terms of the loop variable. 

```

# Task 4
```{r}
library(ggplot2)
# This loads ggplot 
ggplot(data=mtcars, aes(x=as.factor(gear), y=mpg, fill=gear)) + geom_boxplot()
# The function ggplot initiates a new plot. Data used is mtcars. Graph represents miles per gallon as a fuctnion of then number of gears
# fill is used to fill in gears
# geom_boxplot determines the graph to be a boxplot.

```

# Task 5
```{r}
y<- cars$dist; x<- cars$speed
type<- lm(formula = "y~x")
type
# distance from cars data set assigned variable y. speed from cars data set assigned variable x.

summary(type)

#Intercept: -17.5791 Fitted Slope: 3.9324 Standard Deviation Speed: 0.4155 Standard Deviation Distance: 6.7584
```

# Task 6
```{r}
library(grid)
library(gridExtra)
library(gtable)
lm.scatter <- ggplot(cars, aes(x=speed, y=dist)) +
  geom_point(color='#2980B9', size = 4) + xlim(c(0, 25)) +
  geom_smooth(method=lm, se=FALSE, fullrange=TRUE, color='#2C3E50') + 
  labs(title='Linear relationship Between Speed and Breaking Distance')
grid.arrange(lm.scatter)
# grid, girdExtra and gtable is loaded

```

# Task 7
```{r}
new_speed <- cars$speed * (5280/3600)
line<-lm(dist ~ 0+ new_speed + I(new_speed^2),cars)
summary(line)
# 
```

```{r}
library(ggplot2)
# This loads ggplot
y <- cars$dist; x <- cars$new_speed
# Distance in car data is assigned variable y; The variable new_speed is assigned the variable x
ggplot(cars,aes(new_speed,dist)) +
  geom_point(color='Black', size = 1) + xlim(c(0,40)) +
  geom_smooth(method = "lm", formula = "y ~ 0 + x + I(x^2)",  color="red", fullrange='TRUE') + labs(title= 'Reaction Time for Driver to Start Breaking ', y = 'Stopping Distance (feet)', x = "Speed")
# first line initates ggplot using car data set. x is new_speed and y is distance
# second line plots a scatter plot. colour of dots black and size is 1. 
# xlim is used to set the x-axis limits (between 0 to 40)
# The result 0.84479 is a resonable reaction speed
```